[build]
  publish = "/opt/build/repo"
  publishOrigin = "ui"
  functions = "/opt/build/repo/netlify/functions"

[[plugins]]
  package = "@netlify/plugin-functions-serviceworker"
  origin = "config"
  inputs = {}
